services:
  db:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mlapp
      MYSQL_USER: mlapp
      MYSQL_PASSWORD: mlapp
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: mlapp
      PMA_PASSWORD: mlapp
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysqldata:
